{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled $service.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kai.fullname" $ }}-{{ $serviceName }}
  namespace: {{ include "kai.namespace" $ }}
  labels:
    {{- include "kai.labels" $ | nindent 4 }}
    {{- include "kai.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $service.component | default $serviceName }}
  {{- with $service.networkPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "kai.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $service.component | default $serviceName }}
  policyTypes:
    {{- if $service.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if $service.networkPolicy.egress }}
    - Egress
    {{- end }}
  {{- if $service.networkPolicy.ingress }}
  ingress:
    {{- range $service.networkPolicy.ingress }}
    - {{- if .from }}
      from:
        {{- range .from }}
        {{- if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
        {{- end }}
        {{- if .ipBlock }}
        - ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          {{- if .port }}
          port: {{ .port }}
          {{- end }}
          {{- if .endPort }}
          endPort: {{ .endPort }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if $service.networkPolicy.egress }}
  egress:
    {{- range $service.networkPolicy.egress }}
    - {{- if .to }}
      to:
        {{- range .to }}
        {{- if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
        {{- end }}
        {{- if .ipBlock }}
        - ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          {{- if .port }}
          port: {{ .port }}
          {{- end }}
          {{- if .endPort }}
          endPort: {{ .endPort }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

{{- end }}
{{- end }}