apiVersion: apps/v1
kind: Deployment
metadata:
  name: relationship-aware-training
  labels:
    app: relationship-aware-training
    component: ml-services
spec:
  replicas: 1  # Start with 1 replica - will be autoscaled
  selector:
    matchLabels:
      app: relationship-aware-training
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: relationship-aware-training
        component: ml-services
        gpu-enabled: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: relationship-aware-training
        image: ghcr.io/basilakis/kai/kai/relationship-aware-training:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9100
          name: metrics
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu: 1
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: relationship-aware-training-config
              key: log_level
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: relationship-aware-training-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: relationship-aware-training-config
              key: redis_port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: relationship-aware-training-secrets
              key: redis_password
        - name: MODEL_CACHE_DIR
          value: "/models/cache"
        - name: TORCH_HOME
          value: "/models/torch"
        - name: USE_CUDA
          value: "true"
        - name: MAX_CONCURRENT_JOBS
          valueFrom:
            configMapKeyRef:
              name: relationship-aware-training-config
              key: max_concurrent_jobs
        - name: MAX_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: relationship-aware-training-config
              key: max_batch_size
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: models-volume
          mountPath: /models
        - name: shared-data-volume
          mountPath: /shared-data
      volumes:
      - name: config-volume
        configMap:
          name: relationship-aware-training-config
      - name: models-volume
        persistentVolumeClaim:
          claimName: relationship-models-pvc
      - name: shared-data-volume
        persistentVolumeClaim:
          claimName: ml-shared-data-pvc
      # Use node with appropriate GPU
      nodeSelector:
        gpu-type: nvidia-l40s
      # Use RuntimeClass for GPU support
      runtimeClassName: nvidia-gpu
---
apiVersion: v1
kind: Service
metadata:
  name: relationship-aware-training
  labels:
    app: relationship-aware-training
    component: ml-services
spec:
  selector:
    app: relationship-aware-training
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: metrics
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relationship-models-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: managed-premium
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: relationship-aware-training-config
data:
  log_level: "info"
  redis_host: "redis-master.kai.svc.cluster.local"
  redis_port: "6379"
  max_concurrent_jobs: "2"
  max_batch_size: "4"
  model_config.json: |
    {
      "defaultOptions": {
        "includeRelationships": true,
        "relationshipTypes": ["correlates_with", "depends_on", "compatibility"],
        "relationshipStrengthThreshold": 0.3,
        "maxRelationshipDepth": 2,
        "useTransferLearning": true,
        "epochs": 50,
        "batchSize": 32,
        "learningRate": 0.001,
        "validationSplit": 0.2
      },
      "materialTypes": {
        "tile": {
          "defaultTargetProperty": "finish",
          "recommendedProperties": ["finish", "color", "texture", "pattern"]
        },
        "wood": {
          "defaultTargetProperty": "finish",
          "recommendedProperties": ["finish", "color", "grain", "hardness"]
        },
        "stone": {
          "defaultTargetProperty": "finish",
          "recommendedProperties": ["finish", "color", "texture", "density"]
        }
      }
    }
