# GitHub Actions configuration file
# This file helps the linter understand the workflow configuration

# Define the environment variables used in the workflows
runtime:
  # Environment variables set during workflow
  env:
    DEPLOY_ENV: staging
    TAG_SUFFIX: staging
    VERCEL_ARGS: --prod
    API_URL: https://api.kai.example.com
    TEST_SCRIPT: test:e2e
    KUBE_CONTEXT: kubernetes-cluster1

  # Repository secrets
  secrets:
    KUBE_CONFIG_DATA: base64-encoded-kubeconfig
    SUPABASE_URL_PRODUCTION: https://production.supabase.co
    SUPABASE_KEY_PRODUCTION: production-key
    SUPABASE_URL_STAGING: https://staging.supabase.co
    SUPABASE_KEY_STAGING: staging-key
    VERCEL_TOKEN: vercel-token
    VERCEL_ORG_ID: org-id
    VERCEL_PROJECT_ID_CLIENT: client-project-id
    VERCEL_PROJECT_ID_ADMIN: admin-project-id
    SLACK_WEBHOOK: https://hooks.slack.com/services/xxx/yyy/zzz
