apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wasm-compiler-hpa
  namespace: kai-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wasm-compiler
  minReplicas: 2 # Ensure at least 2 replicas are running
  maxReplicas: 5 # Scale up to 5 replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Target 70% CPU utilization