apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mobile-optimization-hpa
  namespace: kai-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mobile-optimization
  minReplicas: 2 # Ensure at least 2 replicas are running
  maxReplicas: 6 # Scale up to 6 replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Target 70% CPU utilization