apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-server
  namespace: flux-system # Flux resources live here
spec:
  interval: 5m # Check for updates every 5 minutes
  chart:
    spec:
      chart: api-server # Name of the subchart
      version: ">=0.1.0" # Use version 0.1.0 or newer
      sourceRef:
        kind: HelmRepository
        name: kai-charts # Reference the HelmRepository source defined in sources/
        namespace: flux-system
      interval: 1m # Check for new chart versions every minute
  # Values passed to the api-server subchart
  # These values will be merged with the subchart's values.yaml
  # and the parent chart's values-staging.yaml
  values:
    # Image tag will be updated by CI/CD
    image:
      repository: "{{ .Values.global.registry.url }}/{{ .Values.global.registry.username }}/kai-api-server" # Construct full image path
      # tag: is set by CI/CD pipeline in this file

    # Staging specific overrides (can be empty if defaults are fine)
    replicaCount: 1 # Explicitly set staging replica count

    # Example of passing global values down if needed, though Helm does this automatically
    # global:
    #   environment: "{{ .Values.global.environment }}"

  # Target namespace where the api-server should be deployed
  targetNamespace: "{{ .Values.global.namespace }}" # Get namespace from parent chart's values

  # Release name in the target namespace
  releaseName: api-server

  # Install/Upgrade/Rollback configuration
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true # Attempt to roll back on failure
    cleanupOnFail: true
  rollback:
    timeout: 5m
    cleanupOnFail: true

  # Depends on other releases if necessary
  # dependsOn:
  #   - name: infrastructure # Example: wait for infrastructure chart
  #     namespace: flux-system