apiVersion: v1
kind: ConfigMap
metadata:
  name: coordinator-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
data:
  redis_host: {{ .Values.config.redis.host | quote }}
  redis_port: {{ .Values.config.redis.port | quote }}
  log_level: {{ .Values.config.logLevel | quote }}
  workflow_namespace: {{ .Values.config.workflowNamespace | quote }}
  environment: {{ .Values.global.environment | quote }}