apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: coordinator-service
    component: orchestration
    {{- include "coordinator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: coordinator-service
      {{- include "coordinator.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: coordinator-service
        component: orchestration
        {{- include "coordinator.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "coordinator.serviceAccountName" . }}
      containers:
      - name: coordinator
        image: "{{ .Values.global.registry.url }}/kai/coordinator-service:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: NODE_ENV
          value: {{ .Values.global.environment }}
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: coordinator-config
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: coordinator-config
              key: redis_port
        - name: WORKFLOW_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: coordinator-config
              key: workflow_namespace
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: coordinator-config
              key: log_level
        # Secrets as environment variables
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coordinator-secrets
              key: redis_password
        # Add additional environment variables as needed
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coordinator/config
          readOnly: true
        - name: cache-volume
          mountPath: /var/cache/coordinator
      volumes:
      - name: config-volume
        configMap:
          name: coordinator-config
      - name: cache-volume
        emptyDir: {}
      # Affinity for better pod distribution
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - coordinator-service
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.nodeSelector }}
      # Use node selectors to run on appropriate nodes
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      # Set appropriate tolerations based on node taints
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}