apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: coordinator-service
    component: orchestration
    {{- include "coordinator.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.metricsPort }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  - port: {{ .Values.service.metricsPort }}
    targetPort: {{ .Values.service.metricsPort }}
    protocol: TCP
    name: metrics
  selector:
    app: coordinator-service
    {{- include "coordinator.selectorLabels" . | nindent 4 }}