apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  releaseName: argo-workflows
  chart:
    spec:
      chart: argo-workflows
      version: '0.45.8'
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
  interval: 10m
  targetNamespace: argo
  install:
    createNamespace: true
