apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coordinator-service-hpa
  namespace: kai-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coordinator-service
  minReplicas: 2 # Ensure at least 2 replicas are running
  maxReplicas: 5 # Scale up to 5 replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75 # Target 75% CPU utilization
  # Optionally add memory-based scaling
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 75