apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mobile-optimization-hpa
  labels:
    app: mobile-optimization
    component: ml-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mobile-optimization
  minReplicas: 2
  maxReplicas: 6
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Processing time-based scaling
  - type: Pods
    pods:
      metric:
        name: ml_processing_time_seconds
      target:
        type: AverageValue
        averageValue: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
