apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mobile-optimization-pdb
spec:
  minAvailable: 1 # Ensure at least 1 replica is always available
  selector:
    matchLabels:
      app: mobile-optimization
