# Default values for coordinator subchart
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

# ServiceAccount configuration
serviceAccount:
  create: true
  name: "coordinator-service-account"
  annotations: {}

# Deployment configuration
replicaCount: 1
minReplicas: 1
maxReplicas: 5
pdbMinAvailable: 1

# Image configuration is inherited from parent chart's global values

# Resource configuration
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# Node selector
nodeSelector:
  node-type: orchestration

# Tolerations
tolerations:
- key: "node-type"
  operator: "Equal"
  value: "orchestration"
  effect: "NoSchedule"

# Configuration for Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Service configuration
service:
  type: ClusterIP
  port: 80
  metricsPort: 8081

# Config and secret values
config:
  redis:
    host: "redis-master"
    port: "6379"
  logLevel: "info"
  workflowNamespace: "kai-workflows"

# Additional pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"