apiVersion: v1
kind: ConfigMap
metadata:
  name: coordinator-config
  labels:
    app: coordinator-service
    component: orchestration
data:
  # Redis configuration
  redis_host: "redis-master.kai.svc.cluster.local"
  redis_port: "6379"
  
  # Workflow configuration
  workflow_namespace: "kai"
  workflow_archive_ttl: "168h"  # Keep workflow history for 7 days
  
  # Logging configuration
  log_level: "info"
  log_format: "json"
  
  # Resource allocation settings
  resource_quota_mode: "fair-share"
  enable_preemption: "true"
  
  # Caching configuration
  enable_caching: "true"
  cache_ttl: "24h"
  
  # Autoscaling configuration
  enable_autoscaling: "true"
  scale_down_delay: "10m"
  
  # Priority configuration
  default_priority: "medium"
  
  # Task queue configuration
  task_queue_config: |
    {
      "queues": {
        "interactive": {
          "maxConcurrent": 10,
          "weight": 100
        },
        "batch": {
          "maxConcurrent": 20,
          "weight": 50
        },
        "maintenance": {
          "maxConcurrent": 5,
          "weight": 10
        }
      }
    }
  
  # Quality tiers configuration
  quality_tiers: |
    {
      "low": {
        "resources": {
          "cpu": "500m",
          "memory": "2Gi",
          "gpu": "0"
        },
        "timeout": "5m"
      },
      "medium": {
        "resources": {
          "cpu": "2",
          "memory": "4Gi",
          "gpu": "0.5"
        },
        "timeout": "15m"
      },
      "high": {
        "resources": {
          "cpu": "4",
          "memory": "8Gi",
          "gpu": "1"
        },
        "timeout": "30m"
      },
      "premium": {
        "resources": {
          "cpu": "8",
          "memory": "16Gi",
          "gpu": "1"
        },
        "timeout": "60m",
        "gpu_class": "nvidia-l40s"
      },
      "enterprise": {
        "resources": {
          "cpu": "16",
          "memory": "32Gi",
          "gpu": "1"
        },
        "timeout": "120m",
        "gpu_class": "nvidia-h100"
      }
    }
  
  # New Features Configuration
  
  # Notification System Configuration
  notification_system: |
    {
      "enabled": true,
      "endpoint": "http://notification-service:8080/api/v1",
      "channels": ["in-app", "email", "sms", "webhook"],
      "defaultChannel": "in-app",
      "events": [
        "task.queued",
        "task.started",
        "task.completed",
        "task.failed",
        "resource.quota.exceeded"
      ],
      "webhook": {
        "endpoint": "http://webhook-service:8080/api/v1",
        "retryAttempts": 3,
        "timeoutMs": 5000
      }
    }
  
  # Parameter Registry Configuration
  parameter_registry: |
    {
      "enabled": true,
      "endpoint": "http://parameter-registry-service:8080/api/v1",
      "grpcEndpoint": "parameter-registry-service:9090",
      "similarityThreshold": 0.75,
      "defaultParameterSet": "standard",
      "historyRetentionDays": 90
    }
  
  # ML Features Configuration
  ml_features: |
    {
      "multimodalPatternRecognition": {
        "enabled": true,
        "workflowTemplate": "multimodal-pattern-recognition-template",
        "minQualityTier": "medium",
        "resourceQuotas": {
          "cpu": 8,
          "memory": "16Gi",
          "gpu": 1
        },
        "maxConcurrent": 4
      },
      "domainSpecificNetworks": {
        "enabled": true,
        "workflowTemplate": "domain-specific-networks-template",
        "minQualityTier": "medium",
        "resourceQuotas": {
          "cpu": 8,
          "memory": "16Gi",
          "gpu": 1
        },
        "maxConcurrent": 4,
        "supportedDomains": ["wood", "metal", "fabric", "stone", "ceramic", "composite"]
      }
    }
  
  # GPU Resource Management
  gpu_resources: |
    {
      "classes": {
        "nvidia-l40s": {
          "priority": 10,
          "models": ["multimodal-pattern-recognition", "domain-specific-networks"]
        },
        "nvidia-h100": {
          "priority": 20,
          "models": ["gaussian-splatting", "triposr", "wonder3d", "instant3d"]
        }
      },
      "scaling": {
        "enabled": true,
        "minNodes": 1,
        "maxNodes": 10,
        "scaleDownDelay": "10m"
      }
    }
  # Workflow templates path
  workflow_templates_path: "/etc/coordinator/config/workflow-templates"
  
  # Monitoring configuration
  prometheus_enabled: "true"
  tracing_enabled: "true"
