---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coordinator-service-account
  labels:
    app: coordinator-service
    component: orchestration

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coordinator-workflow-manager
  labels:
    app: coordinator-service
    component: orchestration
rules:
  # Workflow permissions - allow creating and managing Argo workflows
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - workfloweventbindings
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  
  # Pod permissions - allow listing and watching pods
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/status
    verbs:
      - get
      - list
      - watch
  
  # ConfigMap permissions - allow reading coordinator configuration
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  
  # Secret permissions - allow reading coordinator secrets
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  
  # Event permissions - allow creating and updating events
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  
  # PersistentVolumeClaim permissions - allow creating and managing PVCs for workflow data
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coordinator-workflow-manager-binding
  labels:
    app: coordinator-service
    component: orchestration
subjects:
  - kind: ServiceAccount
    name: coordinator-service-account
    namespace: kai
roleRef:
  kind: Role
  name: coordinator-workflow-manager
  apiGroup: rbac.authorization.k8s.io

---
# Cluster-level permissions for the Coordinator Service
# Only add these if necessary for cross-namespace operations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coordinator-cluster-monitor
  labels:
    app: coordinator-service
    component: orchestration
rules:
  # Node permissions - allow monitoring nodes for resource allocation
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
    verbs:
      - get
      - list
      - watch
  
  # Custom metrics permissions - allow reading custom metrics for scaling decisions
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
  
  # Custom metrics API permissions
  - apiGroups:
      - "custom.metrics.k8s.io"
    resources:
      - "*"
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coordinator-cluster-monitor-binding
  labels:
    app: coordinator-service
    component: orchestration
subjects:
  - kind: ServiceAccount
    name: coordinator-service-account
    namespace: kai
roleRef:
  kind: ClusterRole
  name: coordinator-cluster-monitor
  apiGroup: rbac.authorization.k8s.io
