apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
  namespace: kai-ml
  labels:
    app: coordinator-service
    component: orchestration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: coordinator-service