apiVersion: v2
name: kai
description: Kai Platform - 3D Visualization and ML Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

# Dependencies for subcharts
dependencies:
  - name: coordinator
    version: 0.1.0
    repository: "file://../coordinator"
    condition: coordinator.enabled
  - name: infrastructure
    version: 0.1.0
    repository: "file://../infrastructure"
    condition: infrastructure.enabled
  - name: mobile-optimization
    version: 0.1.0
    repository: "file://../mobile-optimization"
    condition: mobile-optimization.enabled
  - name: wasm-compiler
    version: 0.1.0
    repository: "file://../wasm-compiler"
    condition: wasm-compiler.enabled
  - name: workflows
    version: 0.1.0
    repository: "file://../workflows"
    condition: workflows.enabled
  - name: api-server
    version: 0.1.0
    repository: "file://../api-server"
    condition: api-server.enabled

maintainers:
  - name: Kai Platform Team
    email: devops@kaicorp.com