name: Build and Test

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '20.x'
    secrets:
      npm_token:
        required: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables
        uses: ./.github/actions/load-env
        with:
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

      - name: Set up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Run linting
        run: yarn lint

      - name: Run unit tests
        run: yarn test

      - name: Run integration tests
        run: yarn test:integration

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            packages/*/dist
            packages/*/build
          retention-days: 1