name: Build and Deploy Docusaurus Documentation

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Message for the deployment PR'
        required: true
        default: 'Update documentation'

jobs:
  build_and_deploy_docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Create Docusaurus site
        run: node readme/scripts/create-docusaurus-site.js

      - name: Process readme files
        run: |
          mkdir -p kai-docs-temp/docs
          cd readme
          node process-readme-files.js || echo "Warning: Some readme files may not have been processed correctly"

          # Remove broken links
          node scripts/remove-broken-links.js || echo "Warning: Some markdown links could not be fixed"

      - name: Install Docusaurus dependencies
        run: |
          cd kai-docs-temp
          npm install --no-save @docusaurus/core@3.7.0 @docusaurus/preset-classic@3.7.0 @mdx-js/react@3.0.0 clsx@2.1.0 prism-react-renderer@2.3.1 react@18.2.0 react-dom@18.2.0

      - name: Build Docusaurus site
        run: |
          cd kai-docs-temp
          npx docusaurus build

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Prepare branch
        run: node readme/scripts/prepare-docs-branch.js
        env:
          DOCS_DEPLOY_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          DEPLOY_MESSAGE: ${{ github.event.inputs.deploy_message }}

      - name: Create PR
        run: node readme/scripts/create-docs-pr.js
        env:
          DOCS_DEPLOY_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
          DEPLOY_MESSAGE: ${{ github.event.inputs.deploy_message }}
